### ISSUE TITLE
original name of node changed. Request solution to retain the OTU name.

### ISSUE THREAD

**Issue by balaphd** [zdk123/SpiecEasi#25] opened 2017-10-26 11:30 UTC
Hi,

The solution #23  solved the error and thanks a lot! One more problem arise when
I used the below code:

sparcc.out <-
sparcc(t(as.matrix(otu_table(phyloseqobj.f))),iter=100,inner_iter = 10)
sparcc.graph <- abs(sparcc.out$Cor) >= 0.5
diag(sparcc.graph) <- 0
sparcc.graph <- Matrix(sparcc.graph,sparse=TRUE)
ig.sparcc <- adj2igraph(sparcc.graph)
write_graph(ig.sparcc,file="pre.renov.20.network.sparCC.graphml","graphml")

The original name of the greengenes OTUs were modified as n1,n2,n3...nx and
I don't have any clue which part of your code does this in the sparcc()
function. Could you please check the above code and let me know how to
retain the original OTU name for the nodes.

Best Regards,
Bala

**Comment by zdk123** [comment] 2017-10-26 11:51
Taxa names are not preserved as row/col names, but order of the features
is. You can reassign those names to the output graph.

On Oct 26, 2017 7:30 AM, "balaphd" <notifications@github.com> wrote:

Hi,

The solution solved the error and thanks a lot! One more problem arise when
I used the below code:

sparcc.out <-
sparcc(t(as.matrix(otu_table(phyloseqobj.f))),iter=100,inner_iter = 10)
sparcc.graph <- abs(sparcc.out$Cor) >= 0.5
diag(sparcc.graph) <- 0
sparcc.graph <- Matrix(sparcc.graph,sparse=TRUE)
ig.sparcc <- adj2igraph(sparcc.graph)
write_graph(ig.sparcc,file="pre.renov.20.network.sparCC.graphml","graphml")

The original name of the greengenes OTUs were modified as n1,n2,n3...nx and
I don't have any clue which part of your code does this in the sparcc()
function. Could you please check the above code and let me know how to
retain the original OTU name for the nodes.

Best Regards,
Bala

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zdk123/SpiecEasi/issues/25>, or mute the thread

**Comment by balaphd** [comment] 2017-10-26 12:04
So, for example if the order in my phyloseq object is:

OTU1
OTU2
.
.
.
OTUN


The same will be represented as n1,n2,...nN??

OTU1 = n1
OTU2 = n2
.
.
.
OTUn = nN

Am i correct? Correct me if i understood wrongly. 

Is there any simple trick (one liner) in R which does that? Any help is greatly appreciated!

Best Regards,
Bala

**Comment by zdk123** [comment] 2017-10-26 13:02
rownames (sparcc.graph) <- taxa_names(phyloseqobj.f)

By the way, you should be passing the unnormalized counts to
sparCC/SpiecEasi. Judging from your phyloseq object name i suspect you may
jave total sum normalized.


On Oct 26, 2017 8:04 AM, "balaphd" <notifications@github.com> wrote:

So, for example if the order in my phyloseq object is:

OTU1
OTU2
.
.
.
OTUN

The same will be represented as n1,n2,...nN??

OTU1 = n1
OTU2 = n2
.
.
.
OTUn = nN

Am i correct? Correct me if i understood wrongly.

Is there any simple trick (one liner) in R which does that? Any help is
greatly appreciated!

Best Regards,
Bala

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zdk123/SpiecEasi/issues/25#issuecomment-339643987>, or mute
the thread

**Comment by balaphd** [comment] 2017-10-26 13:30
Hi,

Thanks for the suggestion! I integrate in the code and I still have the
problem because of the added rownames disappear as below in igraph (I think
adj2igraph removes the rownames):

> sparcc.graph
290 x 290 sparse Matrix of class "dsCMatrix"


1050608 . 1 1 . . . . . . . . 1 . . . . . . . . . . . 1 . 1 . . 1 . . . . .
. . . . ......
1033426 1 . . . . . . . . . . 1 . . . 1 . . . . . . . 1 . . . . . . . 1 . .
. . . . ......
505587  1 . . . . . . . . . . 1 . . . . . . 1 . . . . . . . . . 1 . . . . .
. . . . ......
919487  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
180752  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
1051744 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
281220  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
810959  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
137183  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
283765  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1
. . . . ......
367851  . . . . . . . . . . . . . . . . . . . . . . . 1 . . . . . . . . . .
. . . . ......
819037  1 1 1 . . . . . . . . . . . . 1 . . . . . . . 1 . 1 . . . . . 1 . .
. . . . ......
912669  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......

 ..............................
 ........suppressing columns and rows in show(); maybe adjust
'options(max.print= *, width = *)'
 ..............................



1002005 . . 1 . . . . . . 1 . . . . . . . . . . . 1 . . . . . . 1 . . . . 1
. . . . ......
546690  . . . . . . . . 1 . . . . . . . . . . . . . . . . . . . . . . 1 . .
. . . . ......
587616  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
1010721 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
557974  . 1 . . . . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . .
. . . . ......
922761  . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1 . . . . .
. . . . ......
706432  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
993474  1 1 . . . . . . . . . 1 . . . 1 . . . . . . 1 1 . . . . . . . 1 . .
1 . . . ......
1060517 . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1 . . . . .
. . . . ......
12541   . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
969805  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
. . . . ......
1059729 . 1 . . . . . . . . . . . . . . . . . . 1 . 1 1 1 . . . . . . 1 . .
1 . . . ......
0       . . . . . . . . . . . . . . . . . . . . . . . 1 . . . . . . . . . .
. . . . ......
> ig.sparcc
IGRAPH 0c864c8 UNW- 290 2124 --
+ attr: name (v/c), weight (e/n)
+ edges from 0c864c8 (vertex names):
 [1] 1--2   1--3   1--12  1--24  1--26  1--29  1--50  1--52  1--56  1--57
 1--69  1--101
[13] 1--114 1--115 1--119 1--128 1--147 1--154 1--156 1--161 1--163 1--165
1--178 1--180
[25] 1--181 1--191 1--195 1--197 1--211 1--222 1--228 1--232 1--236 1--240
1--246 1--268
[37] 1--276 1--285 2--12  2--16  2--24  2--32  2--66  2--75  2--84  2--85
 2--89  2--94
[49] 2--96  2--100 2--101 2--102 2--115 2--119 2--121 2--128 2--133 2--136
2--138 2--145
[61] 2--147 2--148 2--151 2--154 2--156 2--158 2--161 2--168 2--170 2--180
2--181 2--195
[73] 2--200 2--204 2--208 2--210 2--211 2--219 2--222 2--228 2--230 2--231
2--232 2--233
[85] 2--236 2--247 2--251 2--252 2--259 2--263 2--264 2--266 2--268 2--269
2--275 2--276
+ ... omitted several edges



Below is my code:

#######
sparcc.out <- sparcc(t(as.matrix(otu_table(*phyloseqobj.f)*)),iter=100,inner_iter
= 10)
sparcc.graph <- abs(sparcc.out$Cor) >= 0.5
diag(sparcc.graph) <- 0
sparcc.graph <- Matrix(sparcc.graph,sparse=TRUE)
rownames(sparcc.graph) <- taxa_names(phyloseqobj.f)
ig.sparcc <- adj2igraph(sparcc.graph)
write_graph(ig.sparcc,file="pre.renov.20.network.sparCC.graphml","graphml",row.names(sparcc.graph))
########


Regarding the total sum normalized, I used filterTaxonMatrix() and below is
my code for the phyloseq object:

#################### SPIEC-easi ANALYSIS #################
library(devtools)
install_github("zdk123/SpiecEasi")
library(SpiecEasi)
source('http://bioconductor.org/biocLite.R')
biocLite('phyloseq')
library(phyloseq)
install_github("hallucigenia-sparsa/seqtime")
library(seqtime)
setwd("/Users/balathl/phd.work/preliminary.results/spieceasi")
input.path="/Users/balathl/phd.work/preliminary.results/spieceasi"
output.path="/Users/balathl/phd.work/preliminary.results/spieceasi"
biom.path=file.path(input.path,"otu.table.hotes.pre.renov.20.closed.otus.min00005.json.biom")
phyloseqobj=import_biom(biom.path)
otus=otu_table(phyloseqobj)
taxa=tax_table(phyloseqobj)
filterobj=filterTaxonMatrix(otus,minocc=15,keepSum = FALSE,
return.filtered.indices = TRUE)
otus.f=filterobj$mat
taxa.f=taxa[setdiff(1:nrow(taxa),filterobj$filtered.indices),]
taxa.f=rbind(taxa.f,dummyTaxonomy)
dummyTaxonomy=c("k__","p__","c__","o__","f__","g__","s__")
taxa.f=rbind(taxa.f,dummyTaxonomy)
rownames(taxa.f)[nrow(taxa.f)]="0"
rownames(otus.f)[nrow(otus.f)]="0"
updatedotus=otu_table(otus.f, taxa_are_rows = TRUE)
updatedtaxa=tax_table(taxa.f)
*phyloseqobj.f*=phyloseq(updatedotus, updatedtaxa)
###############

Correct me if I am doing something wrong in the above code!

Best Regards,
Bala

**Comment by zdk123** [comment] 2017-10-26 13:40
Apologies, I forgot that my adj2igraph function overwrites vertex
attributes via the vertex.attr option.
Try instead:
adj2igraph(sparcc.graph, vertex.attr=list(name=taxa_names(phyloseqobj.f)))

**Comment by balaphd** [comment] 2017-10-26 14:05
Hi,

It worked! Thanks a ton!

I am going to construct the networks with sparCC, speiceasi(glasso) and
speiceasi(mb) with my own datasets. Then comparing the results as in your
paper published.

*Regarding the total sum normalized, I used filterTaxonMatrix() and below
is my code for the phyloseq object(Let me know if it is correct):*


#################### SPIEC-easi ANALYSIS #################
library(devtools)
install_github("zdk123/SpiecEasi")
library(SpiecEasi)
source('http://bioconductor.org/biocLite.R')
biocLite('phyloseq')
library(phyloseq)
install_github("hallucigenia-sparsa/seqtime")
library(seqtime)
setwd("/Users/balathl/phd.work/preliminary.results/spieceasi")
input.path="/Users/balathl/phd.work/preliminary.results/spieceasi"
output.path="/Users/balathl/phd.work/preliminary.results/spieceasi"
biom.path=file.path(input.path,"otu.table.hotes.pre.
renov.20.closed.otus.min00005.json.biom")
phyloseqobj=import_biom(biom.path)
otus=otu_table(phyloseqobj)
taxa=tax_table(phyloseqobj)
filterobj=filterTaxonMatrix(otus,minocc=15,keepSum = FALSE,
return.filtered.indices = TRUE)
otus.f=filterobj$mat
taxa.f=taxa[setdiff(1:nrow(taxa),filterobj$filtered.indices),]
taxa.f=rbind(taxa.f,dummyTaxonomy)
dummyTaxonomy=c("k__","p__","c__","o__","f__","g__","s__")
taxa.f=rbind(taxa.f,dummyTaxonomy)
rownames(taxa.f)[nrow(taxa.f)]="0"
rownames(otus.f)[nrow(otus.f)]="0"
updatedotus=otu_table(otus.f, taxa_are_rows = TRUE)
updatedtaxa=tax_table(taxa.f)
*phyloseqobj.f*=phyloseq(updatedotus, updatedtaxa)
############### speiceasi(mb) ###########
spiec.out.mb=spiec.easi(phyloseqobj.f,
method="mb",icov.select.params=list(rep.num=50))
spiec.graph.mb=adj2igraph(spiec.out.mb$refit,vertex.attr=list(name=taxa_names(phyloseqobj.f)))
write_graph(spiec.graph.mb,file="pre.renov.20.network.spieceasi.mb.graphml","graphml")
############### speiceasi(glasso) #########
spiec.out.glasso=spiec.easi(phyloseqobj.f,
method="glasso",icov.select.params=list(rep.num=50))
spiec.graph.glasso=adj2igraph(spiec.out.glasso$refit,vertex.attr=list(name=taxa_names(phyloseqobj.f)))
write_graph(spiec.graph.glasso,file="pre.renov.20.network.spieceasi.glasso.graphml","graphml")
############### speiceasi(SparCC) #######
sparcc.out <-
sparcc(t(as.matrix(otu_table(phyloseqobj.f))),iter=100,inner_iter = 10)
sparcc.graph <- abs(sparcc.out$Cor) >= 0.5
diag(sparcc.graph) <- 0
sparcc.graph <- Matrix(sparcc.graph,sparse=TRUE)
renov.sparcc <- adj2igraph(sparcc.graph,
vertex.attr=list(name=taxa_names(phyloseqobj.f)))
write_graph(renov.sparcc,file="pre.renov.20.network.sparCC.graphml","graphml",row.names(sparcc.graph))
#######################################

Correct me if I am doing something wrong in the above code!

Best Regards,
Bala

**Closed** 2017-11-11 20:11 UTC

**Comment by balaphd** [comment] 2017-11-13 09:43
>By the way, you should be passing the unnormalized counts to
sparCC/SpiecEasi. Judging from your phyloseq object name i suspect you may
jave total sum normalized.

Is my below code is valid with speiceasi? I got much less OTU in the final
network constructed from speiceasi compared to the CONET app. I am
wondering whether i am doing something wrong. Any help is greatly
appreciated!!

#################### SPIEC-easi ANALYSIS #################
library(devtools)
install_github("zdk123/SpiecEasi")
library(SpiecEasi)
source('http://bioconductor.org/biocLite.R')
biocLite('phyloseq')
library(phyloseq)
install_github("hallucigenia-sparsa/seqtime")
library(seqtime)
setwd("/Users/balathl/phd.work/preliminary.results/spieceasi")
input.path="/Users/balathl/phd.work/preliminary.results/spieceasi"
output.path="/Users/balathl/phd.work/preliminary.results/spieceasi"
biom.path=file.path(input.path,"otu.table.hotes.pre.renov.
20.closed.otus.min00005.json.biom")
phyloseqobj=import_biom(biom.path)
otus=otu_table(phyloseqobj)
taxa=tax_table(phyloseqobj)
filterobj=filterTaxonMatrix(otus,minocc=15,keepSum = FALSE,
return.filtered.indices = TRUE)
otus.f=filterobj$mat
taxa.f=taxa[setdiff(1:nrow(taxa),filterobj$filtered.indices),]
taxa.f=rbind(taxa.f,dummyTaxonomy)
dummyTaxonomy=c("k__","p__","c__","o__","f__","g__","s__")
taxa.f=rbind(taxa.f,dummyTaxonomy)
rownames(taxa.f)[nrow(taxa.f)]="0"
rownames(otus.f)[nrow(otus.f)]="0"
updatedotus=otu_table(otus.f, taxa_are_rows = TRUE)
updatedtaxa=tax_table(taxa.f)
*phyloseqobj.f*=phyloseq(updatedotus, updatedtaxa)
############### speiceasi(mb) ###########
spiec.out.mb=spiec.easi(phyloseqobj.f, method="mb",icov.select.
params=list(rep.num=50))
spiec.graph.mb=adj2igraph(spiec.out.mb$refit,vertex.
attr=list(name=taxa_names(phyloseqobj.f)))
write_graph(spiec.graph.mb,file="pre.renov.20.network.
spieceasi.mb.graphml","graphml")
############### speiceasi(glasso) #########
spiec.out.glasso=spiec.easi(phyloseqobj.f, method="glasso",icov.select.
params=list(rep.num=50))
spiec.graph.glasso=adj2igraph(spiec.out.glasso$refit,vertex.
attr=list(name=taxa_names(phyloseqobj.f)))
write_graph(spiec.graph.glasso,file="pre.renov.20.network.spieceasi.glasso.
graphml","graphml")
############### speiceasi(SparCC) #######
sparcc.out <- sparcc(t(as.matrix(otu_table(phyloseqobj.f))),iter=100,inner_iter
= 10)
sparcc.graph <- abs(sparcc.out$Cor) >= 0.5
diag(sparcc.graph) <- 0
sparcc.graph <- Matrix(sparcc.graph,sparse=TRUE)
renov.sparcc <- adj2igraph(sparcc.graph, vertex.attr=list(name=taxa_
names(phyloseqobj.f)))
write_graph(renov.sparcc,file="pre.renov.20.network.sparCC.
graphml","graphml",row.names(sparcc.graph))
#######################################

Thanks in advance!

Bala

**Comment by zdk123** [comment] 2017-11-13 16:18
Without a reproducible example, I can't say for sure. Perhaps unconnected
nodes are getting removed. It's also possible that you have non-standard
orientation of your OTU table. Make sure the input matrix to `sparcc` is
samples (rows) x taxa (columns).
