### ISSUE TITLE
Error when try to use getOptBeta

### ISSUE THREAD

**Issue by hmamine** [zdk123/SpiecEasi#74] opened 2019-03-28 09:45 UTC
Hello, 
I am trying to get the data from the spiec.easi output, the code that I run is indicated below.

```
data('amgut2.filt.phy')
spiec.out.mb<- spiec.easi(amgut2.filt.phy, method="mb", verbose=T, nlambda=50, lambda.min.ratio=1e-2, pulsar.params=list(rep.num=50))
Applying data transformations...
Selecting model with pulsar using stars...
Fitting final estimate with mb...
done
>  Mat.mb=as.matrix(symBeta(getOptBeta(spiec.out.mb)))
Error in if (nrow(beta) != ncol(beta)) { : argument is of length zero
```
I would like to get these data to count the number of positive and negative edges and also plot these edges with a different color ([link](http://psbweb05.psb.ugent.be/conet/microbialnetworks/index.php) for further detail) 

```
print(paste0("Nbr_pos_edges=",length(Mat.mb[Mat.mb>0])/2))
print(paste0("Nbr_neg_edges=",length(Mat.mb[Mat.mb<0])/2))
otu.ids=colnames(spiec.out.mb$est$data)
	edges=E(ig2.mb)
	edge.colors=c()
	for(e.index in 1:length(edges)){
		adj.nodes=ends(ig2.mb,edges[e.index])
		xindex=which(otu.ids==adj.nodes[1])
		yindex=which(otu.ids==adj.nodes[2])
		beta=Mat.mb[xindex,yindex]
		if(beta>0){
			edge.colors=append(edge.colors,"darkgreen")
		}else if(beta<0){
			edge.colors=append(edge.colors,"darkred")
		}
	}
	E(ig2.mb)$color=edge.colors
```

I would appreciate any help to figure out the issue.

**Comment by zdk123** [comment] 2019-03-28 14:35
Duplicate of #72 

I have a fix in a fork, but I have not heard from huge developers if they are willing to integrate the changes.
https://github.com/zdk123/huge/tree/betas

If this is critical, you can install my fork/branch via devtools, and override the CRAN version.

**Closed by zdk123** 2019-03-28 14:35 UTC
