### ISSUE TITLE
can not install it successfully

### ISSUE THREAD

**Issue by shinepreventer** [zdk123/SpiecEasi#185] opened 2021-10-08 07:55 UTC
system：opensuse
gcc-fortan：11-4.1
`Downloading GitHub repo zdk123/SpiecEasi@HEAD
✓  checking for file ‘/tmp/Rtmpcgrl6s/remotes3e2c356bc75e/zdk123-SpiecEasi-ff528b2/DESCRIPTION’ ...
─  preparing ‘SpiecEasi’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.1.tar.gz’
   
将程序包安装入‘/home/wzy/R/x86_64-suse-linux-gnu-library/4.1’
(因为‘lib’没有被指定)
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG  -I'/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/Rcpp/include' -I'/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include' -I/usr/local/include   -fpic  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g  -c ADMM.cpp -o ADMM.o
ADMM.cpp: 在函数‘arma::sp_mat SOFTTHRESH2(arma::mat&, const float&, const bool&)’中:
ADMM.cpp:25:9: 警告：unused variable ‘n’ [-Wunused-variable]
   25 |     int n = A.n_cols;
      |         ^
ADMM.cpp: 在函数‘void svdPowSym(arma::mat&, arma::vec&, arma::mat&, arma::mat&, int, int)’中:
ADMM.cpp:36:9: 警告：unused variable ‘l’ [-Wunused-variable]
   36 |     int l = k;
      |         ^
ADMM.cpp:38:9: 警告：unused variable ‘n’ [-Wunused-variable]
   38 |     int n = A.n_cols;
      |         ^
ADMM.cpp: 在函数‘Rcpp::List ADMM(const mat&, const double&, arma::mat&, arma::mat&, arma::mat&, double, int, double, const double&, const double&, const int&, const double&, const double&, const double&, bool)’中:
ADMM.cpp:193:28: 错误：no match for ‘operator=’ (operand types are ‘arma::subview_cols<double>’ and ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’})
  193 |       X.cols(n  , n*2-1) = S;
      |                            ^
In file included from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo:167,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadilloForward.h:48,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadillo.h:29,
                 from ADMM.cpp:1:
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:476:15: 附注：candidate: ‘template<class T1> void arma::subview_cols<eT>::operator=(const arma::Base<eT, T1>&) [with T1 = T1; eT = double]’
  476 |   inline void operator= (const Base<eT,T1>& x);
      |               ^~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:476:15: 附注：  template argument deduction/substitution failed:
ADMM.cpp:193:28: 附注：  ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} is not derived from ‘const arma::Base<double, T1>’
  193 |       X.cols(n  , n*2-1) = S;
      |                            ^
In file included from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo:167,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadilloForward.h:48,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadillo.h:29,
                 from ADMM.cpp:1:
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:479:94: 附注：candidate: ‘template<class T1, class gen_type> typename arma::enable_if2<arma::is_same_type<typename T1::elem_type, eT>::value, void>::result arma::subview_cols<eT>::operator=(const arma::Gen<T1, gen_type>&) [with T1 = T1; gen_type = gen_type; eT = double]’
  479 |   inline typename enable_if2< is_same_type<typename T1::elem_type, eT>::value, void>::result operator=(const Gen<T1,gen_type>& x);
      |                                                                                              ^~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:479:94: 附注：  template argument deduction/substitution failed:
ADMM.cpp:193:28: 附注：  ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} is not derived from ‘const arma::Gen<T1, gen_type>’
  193 |       X.cols(n  , n*2-1) = S;
      |                            ^
In file included from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo:617,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadilloForward.h:48,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadillo.h:29,
                 from ADMM.cpp:1:
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3940:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(const arma::subview<eT>&) [with eT = double]’
 3940 | subview_cols<eT>::operator=(const subview<eT>& X)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3940:48: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const arma::subview<double>&’
 3940 | subview_cols<eT>::operator=(const subview<eT>& X)
      |                             ~~~~~~~~~~~~~~~~~~~^
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3952:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(const arma::subview_cols<eT>&) [with eT = double]’
 3952 | subview_cols<eT>::operator=(const subview_cols<eT>& X)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3952:53: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const arma::subview_cols<double>&’
 3952 | subview_cols<eT>::operator=(const subview_cols<eT>& X)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~^
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3988:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(eT) [with eT = double]’
 3988 | subview_cols<eT>::operator=(const eT val)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3988:38: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘double’
 3988 | subview_cols<eT>::operator=(const eT val)
      |                             ~~~~~~~~~^~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3964:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(const std::initializer_list<_Tp>&) [with eT = double]’
 3964 | subview_cols<eT>::operator=(const std::initializer_list<eT>& list)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3964:62: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const std::initializer_list<double>&’
 3964 | subview_cols<eT>::operator=(const std::initializer_list<eT>& list)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3976:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(const std::initializer_list<std::initializer_list<_Tp> >&) [with eT = double]’
 3976 | subview_cols<eT>::operator=(const std::initializer_list< std::initializer_list<eT> >& list)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3976:87: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const std::initializer_list<std::initializer_list<double> >&’
 3976 | subview_cols<eT>::operator=(const std::initializer_list< std::initializer_list<eT> >& list)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
make: *** [/usr/lib64/R/etc/Makeconf:177：ADMM.o] 错误 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/SpiecEasi’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmpcgrl6s/file3e2c2a0c8a4f/SpiecEasi_1.1.1.tar.gz’ had non-zero exit status
> install.packages("~/下载/SpiecEasi-1.1.0.zip", repos = NULL, type = "win.binary")
将程序包安装入‘/home/wzy/R/x86_64-suse-linux-gnu-library/4.1’
(因为‘lib’没有被指定)
Error in install.packages : cannot install Windows binary packages on this platform
> library(SpiecEasi)
Error in library(SpiecEasi) : ‘SpiecEasi’不是有效的已经安装了的程序包
> install_github("zdk123/SpiecEasi")
Downloading GitHub repo zdk123/SpiecEasi@HEAD
✓  checking for file ‘/tmp/Rtmpcgrl6s/remotes3e2c33ce8dcc/zdk123-SpiecEasi-ff528b2/DESCRIPTION’ ...
─  preparing ‘SpiecEasi’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.1.tar.gz’
   
将程序包安装入‘/home/wzy/R/x86_64-suse-linux-gnu-library/4.1’
(因为‘lib’没有被指定)
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG  -I'/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/Rcpp/include' -I'/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include' -I/usr/local/include   -fpic  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g  -c ADMM.cpp -o ADMM.o
ADMM.cpp: 在函数‘arma::sp_mat SOFTTHRESH2(arma::mat&, const float&, const bool&)’中:
ADMM.cpp:25:9: 警告：unused variable ‘n’ [-Wunused-variable]
   25 |     int n = A.n_cols;
      |         ^
ADMM.cpp: 在函数‘void svdPowSym(arma::mat&, arma::vec&, arma::mat&, arma::mat&, int, int)’中:
ADMM.cpp:36:9: 警告：unused variable ‘l’ [-Wunused-variable]
   36 |     int l = k;
      |         ^
ADMM.cpp:38:9: 警告：unused variable ‘n’ [-Wunused-variable]
   38 |     int n = A.n_cols;
      |         ^
ADMM.cpp: 在函数‘Rcpp::List ADMM(const mat&, const double&, arma::mat&, arma::mat&, arma::mat&, double, int, double, const double&, const double&, const int&, const double&, const double&, const double&, bool)’中:
ADMM.cpp:193:28: 错误：no match for ‘operator=’ (operand types are ‘arma::subview_cols<double>’ and ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’})
  193 |       X.cols(n  , n*2-1) = S;
      |                            ^
In file included from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo:167,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadilloForward.h:48,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadillo.h:29,
                 from ADMM.cpp:1:
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:476:15: 附注：candidate: ‘template<class T1> void arma::subview_cols<eT>::operator=(const arma::Base<eT, T1>&) [with T1 = T1; eT = double]’
  476 |   inline void operator= (const Base<eT,T1>& x);
      |               ^~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:476:15: 附注：  template argument deduction/substitution failed:
ADMM.cpp:193:28: 附注：  ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} is not derived from ‘const arma::Base<double, T1>’
  193 |       X.cols(n  , n*2-1) = S;
      |                            ^
In file included from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo:167,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadilloForward.h:48,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadillo.h:29,
                 from ADMM.cpp:1:
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:479:94: 附注：candidate: ‘template<class T1, class gen_type> typename arma::enable_if2<arma::is_same_type<typename T1::elem_type, eT>::value, void>::result arma::subview_cols<eT>::operator=(const arma::Gen<T1, gen_type>&) [with T1 = T1; gen_type = gen_type; eT = double]’
  479 |   inline typename enable_if2< is_same_type<typename T1::elem_type, eT>::value, void>::result operator=(const Gen<T1,gen_type>& x);
      |                                                                                              ^~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:479:94: 附注：  template argument deduction/substitution failed:
ADMM.cpp:193:28: 附注：  ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} is not derived from ‘const arma::Gen<T1, gen_type>’
  193 |       X.cols(n  , n*2-1) = S;
      |                            ^
In file included from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo:617,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadilloForward.h:48,
                 from /home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/RcppArmadillo.h:29,
                 from ADMM.cpp:1:
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3940:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(const arma::subview<eT>&) [with eT = double]’
 3940 | subview_cols<eT>::operator=(const subview<eT>& X)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3940:48: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const arma::subview<double>&’
 3940 | subview_cols<eT>::operator=(const subview<eT>& X)
      |                             ~~~~~~~~~~~~~~~~~~~^
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3952:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(const arma::subview_cols<eT>&) [with eT = double]’
 3952 | subview_cols<eT>::operator=(const subview_cols<eT>& X)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3952:53: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const arma::subview_cols<double>&’
 3952 | subview_cols<eT>::operator=(const subview_cols<eT>& X)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~^
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3988:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(eT) [with eT = double]’
 3988 | subview_cols<eT>::operator=(const eT val)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3988:38: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘double’
 3988 | subview_cols<eT>::operator=(const eT val)
      |                             ~~~~~~~~~^~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3964:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(const std::initializer_list<_Tp>&) [with eT = double]’
 3964 | subview_cols<eT>::operator=(const std::initializer_list<eT>& list)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3964:62: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const std::initializer_list<double>&’
 3964 | subview_cols<eT>::operator=(const std::initializer_list<eT>& list)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3976:1: 附注：candidate: ‘void arma::subview_cols<eT>::operator=(const std::initializer_list<std::initializer_list<_Tp> >&) [with eT = double]’
 3976 | subview_cols<eT>::operator=(const std::initializer_list< std::initializer_list<eT> >& list)
      | ^~~~~~~~~~~~~~~~
/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3976:87: 附注：  no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const std::initializer_list<std::initializer_list<double> >&’
 3976 | subview_cols<eT>::operator=(const std::initializer_list< std::initializer_list<eT> >& list)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
make: *** [/usr/lib64/R/etc/Makeconf:177：ADMM.o] 错误 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/home/wzy/R/x86_64-suse-linux-gnu-library/4.1/SpiecEasi’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmpcgrl6s/file3e2c12f35d43/SpiecEasi_1.1.1.tar.gz’ had non-zero exit status`

**Comment by zdk123** [comment] 2021-10-08 13:59
duplicate of #183

**Closed by zdk123** 2021-10-08 13:59 UTC
