### ISSUE TITLE
sparccboot very slow

### ISSUE THREAD

**Issue by SimenHyllHansen** [zdk123/SpiecEasi#116] opened 2020-02-12 13:30 UTC
Hi! I've read through the other issues on sparccboot and can't find an answer to any of my questions. 

I have a dataset `A` with 533 taxa and 158 observations. Running `sparcc(A)` on this dataset takes about 50 seconds to complete on my laptop.

To obtain p-values, I wanted to run `B = sparccboot(A, R = 10, ncpus = 1)` followed by `pval.sparccboot(B, sided = "both")` as a test with only 10 bootstraps to test out the method. This took almost 2 hours, and continually used all 8 of my cores at 100% capacity. I have 3 questions regarding this:

1. Is it normal for sparccboot to be this time consuming?

2. Why is sparccboot using all 8 of my CPU cores when ncpus is set to 1?

3. How many bootstraps would be adviceable to get accurate p-values at the standard 0.05 level with this dataset? Generic answers I have seen on stackexchange suggest at least 1000 bootstraps for accurate p-values, however this would indeed take a lot of time to run on my dataset.

Thanks for any help on any of the questions.

-Simen Hyll Hansen

**Comment by zdk123** [comment] 2020-02-12 14:44
Superficially, this is a duplicate of #115. boot::boot is also wrapper around `parallel::mclapply`. Can you try running some function and see if the mc.cores is respected?

For instance:
```
system.time(parallel::mclapply(1:8, function(i) Sys.sleep(time=30), mc.cores=1))
system.time(parallel::mclapply(1:8, function(i) Sys.sleep(time=30), mc.cores=8))
```
I can migrate the code to another package (e.g. `snow`), but so far I haven't been able to reproduce the issue on any system.

**Comment by zdk123** [comment] 2020-02-12 14:48
As to your other question, sparcc is always going to scale quadratically with the number of taxa so bootstrapping is just always going to be slow, even if theoretically we could speed up the underlying code by refactoring or porting to C++ or something. But you could try FastSpar https://github.com/scwatts/fastspar as an alternative to this package.

**Comment by SimenHyllHansen** [comment] 2020-02-13 09:40
Thank you for your quick feedback. Sorry I missed #115 , which also talked about the number of cores. I am not an R expert, but tried defining a function for my dataset data.t.HC like so

````
runningsparccboot = function(dataset, N) {
  sparccboot(dataset, R = N)
}

#testing the function to see if it works
runningsparccboot(data.t.HC, 10)


#testing the function with zdk123's provided code, with 1, 2 and 4 cores
system.time(parallel::mclapply(1:8, runningsparccboot(data.t.HC, 10), Sys.sleep(time=30), mc.cores=1))

system.time(parallel::mclapply(1:8, runningsparccboot(data.t.HC, 10), Sys.sleep(time=30), mc.cores=2))

system.time(parallel::mclapply(1:8, runningsparccboot(data.t.HC, 10), Sys.sleep(time=30), mc.cores=4))
````
In all cases it immediately used all 8 cores at 100% load.

Or did you mean I should run some function not related to the SpiecEasi-package? 



Thank you for the suggestion on FastSpar, will check it out. I guess I could generate the SparCC correlation matrix as well as p-values using FastSpar, and then feed those tables into the R-script I already have to create the same visualizations as before? Using code such as 

```
#build the network
sparcc.net = graph.adjacency(sparcc.adj, mode = "undirected", diag = FALSE, weighted = TRUE)  #originalt uten weighted = TRUE


#subset network so only nodes with a connection is left
clean.net = delete.vertices(sparcc.net, which(degree(sparcc.net, mode = "all") == 0))
sparcc.net = clean.net

sparcc.net.abs = sparcc.net
E(sparcc.net.abs)$weight = abs(E(sparcc.net.abs)$weight)
E(sparcc.net.abs)$weight 
E(sparcc.net)$weight

#HUB DETECTION Hubs are central nodes in the network
net.cn = closeness(sparcc.net.abs)
net.bn = betweenness(sparcc.net.abs)
net.pr = page_rank(sparcc.net)$vector
net.hs = hub_score(sparcc.net)$vector
```

**Comment by zdk123** [comment] 2020-02-13 14:02
> Or did you mean I should run some function not related to the SpiecEasi-package?
Yes, for example the example code I posted.

**Comment by SimenHyllHansen** [comment] 2020-02-13 16:24
Ah, I misunderstood and thought I had to create a new function. Sorry for my inexperience and thanks for bearing with me.

Running your code with 1 and 4 cores seems like it works, so the question remains why this does not work with the sparccboot-function:


```
> system.time(parallel::mclapply(1:8, function(i) Sys.sleep(time=30), mc.cores=1))
   user  system elapsed 
  0.779   0.638 240.005 
> system.time(parallel::mclapply(1:8, function(i) Sys.sleep(time=30), mc.cores=4))
   user  system elapsed 
  0.364   0.319  60.050
```


And just to repeat the question from before in a more concrete format, running the same dataset with FastSpar, filtering the FastSpar-table with the FastSpar-derived p-values, and then feeding the resulting table from FastSpar into R here

```
#original
sparcc.matrix = sparcc(data.t.HC)

#new, using FastSpar-output
sparcc.matrix = read.table([FastSpar-output-matrix],etcetc)
```


..and then continuing with the script as normal, is a valid way of going forward, right?  I would like to avoid using many days of computing time with SpiecEasi's sparccboot if possible.

**Comment by zdk123** [comment] 2020-02-13 16:29
Thanks for the response, I'm now convinced the issue is on my end. I haven't actually tested FastSpar but that seems like a reasonable way forward.

**Closed** 2020-07-13 15:07 UTC
